baseURL = "http://anacunha.dev/"
copyright = "Ana Cunha"
defaultContentLanguage = "pt-br"
googleAnalytics = "G-JWKQF999TS"
googleAnalyticsAsync = true
theme = "cactus"
title = "Ana Cunha"

[languages]
  [languages.pt-br]
    weight = 1

  [languages.en]
    weight = 2

[params]
  colortheme = "classic"
  description = "Software Development & Cloud Computing"
  mainSection = "posts"
  rss = true

  [[params.social]]
    name = "github"
    link = "https://github.com/anacunha"

  [[params.social]]
    name = "twitter"
    link = "https://twitter.com/mcunhaana"

  [[params.social]]
    name = "linkedin"
    link = "https://linkedin.com/in/analuizacunha"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 3

[permalinks]
  posts = "/:year/:filename"
